#!/bin/sh
db2 connect 
db2 drop database GCDDB
echo Creating the database, patience please
db2 CREATE DATABASE GCDDB AUTOMATIC STORAGE YES PAGESIZE 32 K
db2 connect to GCDDB
db2 DROP TABLESPACE USERSPACE1
db2 UPDATE DATABASE CONFIGURATION FOR GCDDB USING APPLHEAPSZ 2560
db2 UPDATE DATABASE CONFIGURATION FOR GCDDB USING CUR_COMMIT ON DEFERRED
db2 CREATE LARGE TABLESPACE "GCD_ts" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE USING STOGROUP IBMSTOGROUP AUTORESIZE YES BUFFERPOOL IBMDEFAULTBP OVERHEAD INHERIT TRANSFERRATE INHERIT DROPPED TABLE RECOVERY ON DATA TAG INHERIT

