#!/bin/sh
db2 connect reset
db2 drop database OS1DB
echo creating the database, patience please
db2 CREATE DATABASE OS1DB AUTOMATIC STORAGE YES PAGESIZE 32 K
db2 connect to OS1DB
db2 DROP TABLESPACE USERSPACE1
db2 UPDATE DATABASE CONFIGURATION FOR OS1DB USING APPLHEAPSZ 2560
db2 UPDATE DATABASE CONFIGURATION FOR OS1DB USING CUR_COMMIT ON DEFERRED
db2 CREATE LARGE TABLESPACE "DATA_ts" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE USING STOGROUP IBMSTOGROUP AUTORESIZE YES BUFFERPOOL IBMDEFAULTBP OVERHEAD INHERIT TRANSFERRATE INHERIT DROPPED TABLE RECOVERY ON DATA TAG INHERIT
